################################################
# These are host specific environment settings.  
# This isnt symlinked anywhere, and I dont put 
# it under version control.
#################################################

# Set up our path first
export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH

# Work around macos's stupid broken ssh-agent
export SSH_AUTH_SOCK=/usr/local/var/run/yubikey-agent.sock

# Set up zsh related env vars
export ZSH="$HOME/.oh-my-zsh"
export ZPLUG_HOME=/usr/share/zplug

# Set up our $DOTFILES env var
export DOTFILES=$HOME/.dotfiles

# Set up our starship prompt configuration location
export STARSHIP_CONFIG=$DOTFILES/starship/starship.toml

# Set up Google Application Creds env variable
#export GOOGLE_APPLICATION_CREDENTIALS = your/path/to/service_account_cred.json

# You may want to manually set your language environment and compilation flags
# export LANG=en_US.UTF-8
# export ARCHFLAGS="-arch x86_64"

# export MANPATH="/usr/local/man:$MANPATH"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vscode -w'
fi

################################################
# Miscellaneous environment variables and
# user settings.
################################################

# Disable fuzzy search for kubectx/kubens
export KUBECTX_IGNORE_FZF=1 

# Display red dots whilst waiting for completions
COMPLETION_WAITING_DOTS="true"

# Disable marking untracked files as dirty. 
# Major speed improvement for git status on large repos
DISABLE_UNTRACKED_FILES_DIRTY="true"

# History command time stamp format
HIST_STAMPS="mm/dd/yyyy"

# Zsh Autosuggest strategy using histdb
ZSH_AUTOSUGGEST_STRATEGY=histdb_top_here

# Uncomment the following line to disable 'column' command 2048 limit workaround
HISTDB_TABULATE_CMD=(sed -e $'s/\x1f/\t/g')
